/// Measure home table. All portfolio analytics measures live here.
table _Measures
	lineageTag: b9d3783d-5c24-599e-a34b-18d15b2f7b90

	/// Count of projects in context.
	measure Projects = COUNTROWS('Project')
		formatString: #,0
		displayFolder: Portfolio
		lineageTag: f308346b-1865-5886-a9b0-7c1a5ae8bd07

	/// Projects with status Active.
	measure 'Active Projects' = CALCULATE([Projects], 'Project'[Project Status] = "Active")
		formatString: #,0
		displayFolder: Portfolio
		lineageTag: e8f16eeb-fb34-546f-9553-873d85c6784d

	/// Projects with status Proposed.
	measure 'Proposed Projects' = CALCULATE([Projects], 'Project'[Project Status] = "Proposed")
		formatString: #,0
		displayFolder: Portfolio
		lineageTag: d2e6aa18-197a-5c0e-bc34-733a79b52c19

	/// Sum of charter-approved budget totals (project.budget_total).
	measure 'Portfolio Charter Budget' = SUM('Project'[Charter Budget])
		formatString: \$#,##0;(\$#,##0);\$0
		displayFolder: Portfolio
		lineageTag: f13a2590-0a02-5218-b72d-13a75d0119b4

	/// Count of schedule activities.
	measure Activities = COUNTROWS('Schedule Activity')
		formatString: #,0
		displayFolder: Schedule
		lineageTag: 13c0a6de-deb2-5251-b7f4-8a8bac3439d0

	/// Activities completed.
	measure 'Activities Done' = CALCULATE([Activities], 'Schedule Activity'[Activity Status] = "Done")
		formatString: #,0
		displayFolder: Schedule
		lineageTag: e176fac5-77e7-5b93-a891-270092b92b21

	/// Activities currently in progress.
	measure 'Activities In Progress' = CALCULATE([Activities], 'Schedule Activity'[Activity Status] = "In progress")
		formatString: #,0
		displayFolder: Schedule
		lineageTag: a91e8eef-945c-59d5-8609-a91757a04d24

	/// Activities flagged at risk.
	measure 'Activities At Risk' = CALCULATE([Activities], 'Schedule Activity'[Activity Status] = "At risk")
		formatString: #,0
		displayFolder: Schedule
		lineageTag: 7d11f723-480a-5d1f-a968-d4bd6b6d1053

	/// Percent complete weighted by activity duration.
	measure 'Pct Complete (Duration Weighted)' = DIVIDE(SUMX('Schedule Activity', 'Schedule Activity'[Duration Days] * 'Schedule Activity'[Pct Complete]), SUMX('Schedule Activity', 'Schedule Activity'[Duration Days]) * 100)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Schedule
		lineageTag: ccb8569b-1c5e-5eb5-bb17-ed8b7e9e1cfb

	/// Open activities past their planned finish date.
	measure 'Activities Overdue' = COUNTROWS(FILTER('Schedule Activity', 'Schedule Activity'[Planned Finish] < TODAY() && NOT 'Schedule Activity'[Activity Status] IN {"Done", "Cancelled"}))
		formatString: #,0
		displayFolder: Schedule
		lineageTag: 56e00548-c516-5bbf-93e5-92577a3b9624

	/// Share of activities overdue.
	measure 'Overdue Pct' = DIVIDE([Activities Overdue], [Activities])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Schedule
		lineageTag: cad61e38-c1df-5775-a814-688b681f41d0

	/// Done activities that finished on or before planned finish.
	measure 'On-Time Completion Pct' = DIVIDE(COUNTROWS(FILTER('Schedule Activity', 'Schedule Activity'[Activity Status] = "Done" && NOT ISBLANK('Schedule Activity'[Actual Finish]) && 'Schedule Activity'[Actual Finish] <= 'Schedule Activity'[Planned Finish])), [Activities Done])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Schedule
		lineageTag: ca6b387a-59e6-5992-b821-22e1bf3033da

	/// Average planned working-day duration.
	measure 'Avg Duration Days' = AVERAGE('Schedule Activity'[Duration Days])
		formatString: #,0.0
		displayFolder: Schedule
		lineageTag: e23fdcd8-4e20-5bfc-a21b-a689e2b3c086

	/// Budget at completion from work-package estimates (wbs_element.estimated_cost). EVM baseline.
	measure 'BAC (WBS Estimates)' = CALCULATE(SUM('WBS Element'[Estimated Cost]), 'WBS Element'[WBS Level] = 2)
		formatString: \$#,##0;(\$#,##0);\$0
		displayFolder: EVM
		lineageTag: 58d1f0b8-f947-54f9-8f84-8b5b83901d34

	/// EV = work-package estimate x mean percent complete of its activities.
	measure 'Earned Value' = SUMX(FILTER('WBS Element', 'WBS Element'[WBS Level] = 2), 'WBS Element'[Estimated Cost] * CALCULATE(AVERAGE('Schedule Activity'[Pct Complete])) / 100)
		formatString: \$#,##0;(\$#,##0);\$0
		displayFolder: EVM
		lineageTag: 65516059-1e26-57cc-9bfb-c7d8c8cd5c0e

	/// PV = work-package estimate x planned-elapsed fraction of its activities as of today.
	measure 'Planned Value' = VAR AsOf = TODAY() RETURN SUMX(FILTER('WBS Element', 'WBS Element'[WBS Level] = 2), 'WBS Element'[Estimated Cost] * CALCULATE(AVERAGEX('Schedule Activity', VAR s = 'Schedule Activity'[Planned Start] VAR f = 'Schedule Activity'[Planned Finish] RETURN IF(AsOf >= f, 1, IF(AsOf <= s, 0, DIVIDE(AsOf - s, f - s))))))
		formatString: \$#,##0;(\$#,##0);\$0
		displayFolder: EVM
		lineageTag: c9f8e5e6-e5ac-521c-897d-7369abb22acb

	/// EV minus PV. Negative = behind schedule.
	measure 'Schedule Variance (SV)' = [Earned Value] - [Planned Value]
		formatString: \$#,##0;(\$#,##0);\$0
		displayFolder: EVM
		lineageTag: 345e0773-c2c2-5d04-b59c-e72209c1cf61

	/// Schedule Performance Index = EV / PV. Below 1.0 = behind schedule. CPI/EAC require a cost-actuals feed (Phase 2 - not in THG-ENT-DBS-001 v1.0).
	measure SPI = DIVIDE([Earned Value], [Planned Value])
		formatString: 0.00
		displayFolder: EVM
		lineageTag: 1c3a2236-054e-593f-8b87-94927e127a19

	/// Count of milestones.
	measure Milestones = COUNTROWS('Milestone')
		formatString: #,0
		displayFolder: Milestones
		lineageTag: 609e8f92-34af-50fc-8da0-37b542df32d7

	/// Milestones achieved.
	measure 'Milestones Achieved' = CALCULATE([Milestones], 'Milestone'[Milestone Status] = "Achieved")
		formatString: #,0
		displayFolder: Milestones
		lineageTag: 198ffad9-30f2-504d-8442-ef1a60ec8b09

	/// Milestones at risk.
	measure 'Milestones At Risk' = CALCULATE([Milestones], 'Milestone'[Milestone Status] = "At risk")
		formatString: #,0
		displayFolder: Milestones
		lineageTag: d3762617-8333-5ad6-89d1-b6a43fc6cec1

	/// Milestones slipped.
	measure 'Milestones Slipped' = CALCULATE([Milestones], 'Milestone'[Milestone Status] = "Slipped")
		formatString: #,0
		displayFolder: Milestones
		lineageTag: 4d405786-f2df-52ac-ab6d-72beb06e09cb

	/// Achieved milestones that landed on or before baseline.
	measure 'Milestone Hit Rate' = DIVIDE(COUNTROWS(FILTER('Milestone', 'Milestone'[Milestone Status] = "Achieved" && NOT ISBLANK('Milestone'[Actual Date]) && 'Milestone'[Actual Date] <= 'Milestone'[Baseline Date])), [Milestones Achieved])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Milestones
		lineageTag: b5b73ab5-9dc8-52c5-bece-464cf1063c80

	/// Mean slip days (actual/forecast vs baseline). Positive = late.
	measure 'Avg Milestone Slip Days' = AVERAGE('Milestone'[Slip Days])
		formatString: #,0.0
		displayFolder: Milestones
		lineageTag: dab88ca5-70ab-5048-9afd-601039d4ecdf

	/// Funded budget including contingency (budget_line_item.total).
	measure 'Budget Total' = SUM('Budget Line'[Total])
		formatString: \$#,##0;(\$#,##0);\$0
		displayFolder: Cost
		lineageTag: 8052388b-eecd-5989-a80b-2a9953f809cd

	/// Budget before contingency.
	measure 'Budget Subtotal' = SUM('Budget Line'[Subtotal])
		formatString: \$#,##0;(\$#,##0);\$0
		displayFolder: Cost
		lineageTag: 7a3f497d-0615-52bb-94d4-4c7c4dc1c8ff

	/// Contingency reserve in the funded budget.
	measure 'Contingency Amount' = [Budget Total] - [Budget Subtotal]
		formatString: \$#,##0;(\$#,##0);\$0
		displayFolder: Cost
		lineageTag: 618b090d-99b3-5b7e-9205-80bdc40e7092

	/// Labor component.
	measure 'Labor Amount' = SUM('Budget Line'[Labor Amount])
		formatString: \$#,##0;(\$#,##0);\$0
		displayFolder: Cost
		lineageTag: fa8526f8-30a6-523d-aaf9-3724d8f2004d

	/// Materials component.
	measure 'Materials Amount' = SUM('Budget Line'[Materials Amount])
		formatString: \$#,##0;(\$#,##0);\$0
		displayFolder: Cost
		lineageTag: 5a4c6464-2d98-505e-8e79-bc3e002f7e00

	/// Vendor / contractor component.
	measure 'Vendor Amount' = SUM('Budget Line'[Vendor Amount])
		formatString: \$#,##0;(\$#,##0);\$0
		displayFolder: Cost
		lineageTag: 51417b76-b312-513f-bbe1-298f77bbf782

	/// Other cost component.
	measure 'Other Amount' = SUM('Budget Line'[Other Amount])
		formatString: \$#,##0;(\$#,##0);\$0
		displayFolder: Cost
		lineageTag: a79f7d26-a5f3-52ee-bd9f-1287afaab408

	/// Net cost impact of approved change requests.
	measure 'Approved CR Cost Impact' = CALCULATE(SUM('Change Request'[Cost Impact]), 'Change Request'[Decision] = "Approved")
		formatString: \$#,##0;(\$#,##0);\$0
		displayFolder: Cost
		lineageTag: af22fa3c-01f0-59d2-a0cc-dc872fd24e0e

	/// Funded budget adjusted for approved change requests.
	measure 'Working Budget' = [Budget Total] + [Approved CR Cost Impact]
		formatString: \$#,##0;(\$#,##0);\$0
		displayFolder: Cost
		lineageTag: 0ce7688e-ae9c-5dd5-a750-f0b9ea35a7cc

	/// Detailed budget vs charter-approved total. Positive = over charter.
	measure 'Budget vs Charter' = [Budget Total] - [Portfolio Charter Budget]
		formatString: \$#,##0;(\$#,##0);\$0
		displayFolder: Cost
		lineageTag: e406b017-b166-5b38-a836-de821c9f3402

	/// Count of risks.
	measure Risks = COUNTROWS('Risk')
		formatString: #,0
		displayFolder: Risk
		lineageTag: 2c601208-1930-5ae0-bf86-0147e98e8f92

	/// Risks not yet closed or realized.
	measure 'Open Risks' = CALCULATE([Risks], 'Risk'[Risk Status] IN {"Open", "Mitigating", "Monitoring"})
		formatString: #,0
		displayFolder: Risk
		lineageTag: 7558ff3b-f1bd-51ac-8900-6431066b84fe

	/// Open risks with score >= 12 on the 5x5 matrix.
	measure 'High Risks' = CALCULATE([Risks], 'Risk'[Risk Score] >= 12, 'Risk'[Risk Status] IN {"Open", "Mitigating", "Monitoring"})
		formatString: #,0
		displayFolder: Risk
		lineageTag: 2791c558-1d40-5d27-b039-b3dc189aeff2

	/// Open risks with score >= 20.
	measure 'Critical Risks' = CALCULATE([Risks], 'Risk'[Risk Score] >= 20, 'Risk'[Risk Status] IN {"Open", "Mitigating", "Monitoring"})
		formatString: #,0
		displayFolder: Risk
		lineageTag: ce031611-ef04-5193-afd3-3e4b4b7eb3a9

	/// Risks that materialized.
	measure 'Realized Risks' = CALCULATE([Risks], 'Risk'[Risk Status] = "Realized")
		formatString: #,0
		displayFolder: Risk
		lineageTag: 506027bb-348f-5814-9043-f21859f191a5

	/// Sum of L x I scores across open risks.
	measure 'Total Risk Exposure' = CALCULATE(SUM('Risk'[Risk Score]), 'Risk'[Risk Status] IN {"Open", "Mitigating", "Monitoring"})
		formatString: #,0
		displayFolder: Risk
		lineageTag: 901eb3c0-f2e2-518c-9b0e-9eecb5d9f40f

	/// Sum of residual scores across open risks (post-mitigation).
	measure 'Residual Exposure' = CALCULATE(SUM('Risk'[Residual Score]), 'Risk'[Risk Status] IN {"Open", "Mitigating", "Monitoring"})
		formatString: #,0
		displayFolder: Risk
		lineageTag: 3ccfae15-8896-5748-b234-74819cc0bd1c

	/// Exposure reduction achieved by planned mitigations.
	measure 'Risk Reduction Pct' = 1 - DIVIDE([Residual Exposure], [Total Risk Exposure])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Risk
		lineageTag: 557fc6e2-0e32-5da4-8bfc-752a088f6b01

	/// Open risks whose mitigation due date has passed.
	measure 'Risks Past Due' = COUNTROWS(FILTER('Risk', NOT ISBLANK('Risk'[Due Date]) && 'Risk'[Due Date] < TODAY() && 'Risk'[Risk Status] IN {"Open", "Mitigating"}))
		formatString: #,0
		displayFolder: Risk
		lineageTag: 3a51dcf7-2871-5f22-9bfa-15657d9dad9a

	/// Mean risk score.
	measure 'Avg Risk Score' = AVERAGE('Risk'[Risk Score])
		formatString: #,0.0
		displayFolder: Risk
		lineageTag: a5865c0e-50e3-54dd-8128-0d4b07790b9e

	/// Risk response actions in context.
	measure 'Response Actions' = COUNTROWS('Risk Response')
		formatString: #,0
		displayFolder: Risk
		lineageTag: eff6df34-0bb0-5a5d-9247-1393237adcff

	/// Risk response actions not yet done.
	measure 'Open Response Actions' = CALCULATE(COUNTROWS('Risk Response'), NOT 'Risk Response'[Action Status] IN {"Done"})
		formatString: #,0
		displayFolder: Risk
		lineageTag: 808d5d77-6f7c-515b-88bf-29ac4470033b

	/// Count of CRs.
	measure 'Change Requests' = COUNTROWS('Change Request')
		formatString: #,0
		displayFolder: Change
		lineageTag: d9160ca7-dcc4-55ec-929e-eaf0d387672f

	/// CRs still in the pipeline.
	measure 'Open CRs' = CALCULATE([Change Requests], NOT 'Change Request'[CR Status] IN {"Closed", "Rejected"})
		formatString: #,0
		displayFolder: Change
		lineageTag: f16b76b3-3049-5a7f-abc5-3135266ee5e1

	/// CRs approved.
	measure 'Approved CRs' = CALCULATE([Change Requests], 'Change Request'[Decision] = "Approved")
		formatString: #,0
		displayFolder: Change
		lineageTag: 2e4d98a2-f50d-5741-8cd3-822a01046cb8

	/// CRs rejected.
	measure 'Rejected CRs' = CALCULATE([Change Requests], 'Change Request'[Decision] = "Rejected")
		formatString: #,0
		displayFolder: Change
		lineageTag: 8015c3b5-aa69-5a26-8cfd-66fc7a6d8a16

	/// CRs awaiting a decision.
	measure 'Pending CRs' = CALCULATE([Change Requests], 'Change Request'[Decision] = "Pending")
		formatString: #,0
		displayFolder: Change
		lineageTag: e63d32d2-806b-568c-a035-e99ae3dc3bb8

	/// Approved share of decided CRs.
	measure 'CR Approval Rate' = DIVIDE([Approved CRs], [Approved CRs] + [Rejected CRs])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Change
		lineageTag: e88b14b8-a2a2-5854-a501-bbf35b0e7a85

	/// Mean days from request to decision.
	measure 'Avg CR Cycle Days' = AVERAGE('Change Request'[Cycle Time Days])
		formatString: #,0.0
		displayFolder: Change
		lineageTag: 62cf493c-37a7-5d9f-ae32-2b1bd874685a

	/// Net schedule delta from approved CRs.
	measure 'Net Schedule Impact Days' = CALCULATE(SUM('Change Request'[Schedule Impact Days]), 'Change Request'[Decision] = "Approved")
		formatString: #,0
		displayFolder: Change
		lineageTag: 3c5a2d2c-5527-50b8-a3b4-7b6b1fc45587

	/// Emergency / safety class CRs.
	measure 'Emergency CRs' = CALCULATE([Change Requests], 'Change Request'[CR Class] = "Emergency / Safety")
		formatString: #,0
		displayFolder: Change
		lineageTag: 49d2bbd3-3a3d-55f5-81ca-d896ddcd884e

	/// Reports submitted.
	measure 'Status Reports' = COUNTROWS('Status Report')
		formatString: #,0
		displayFolder: Health
		lineageTag: 388d0d72-2c2d-5f3b-89a5-56c82552a37a

	/// Most recent reporting period end.
	measure 'Latest Report Date' = MAX('Status Report'[Period End])
		formatString: yyyy-mm-dd
		displayFolder: Health
		lineageTag: b243c6fc-c582-5ea5-9eb0-ba7d1204066a

	/// Overall G/Y/R from the most recent report in context.
	measure 'Latest Overall Status' = VAR d0 = MAX('Status Report'[Period End]) RETURN MAXX(FILTER('Status Report', 'Status Report'[Period End] = d0), 'Status Report'[Overall Status])
		displayFolder: Health
		lineageTag: 16fb1287-ed9c-5a77-b5d0-f91fb98b6d8c

	/// Trend from the most recent report in context.
	measure 'Latest Trend' = VAR d0 = MAX('Status Report'[Period End]) RETURN MAXX(FILTER('Status Report', 'Status Report'[Period End] = d0), 'Status Report'[Trend])
		displayFolder: Health
		lineageTag: 43e954cc-f834-55be-a769-579825cab73d

	/// Mean knowledge-area health: Green=3, Yellow=2, Red=1.
	measure 'Health Score' = AVERAGEX('Status Report Area', SWITCH('Status Report Area'[Area Status], "Green", 3, "Yellow", 2, "Red", 1))
		formatString: 0.00
		displayFolder: Health
		lineageTag: ffd962b2-4175-531c-b99d-b3563cb3f10a

	/// Knowledge-area health entries in context.
	measure 'Area Entries' = COUNTROWS('Status Report Area')
		formatString: #,0
		displayFolder: Health
		lineageTag: 76278add-9a8f-5825-a940-455b00810092

	/// Knowledge-area entries reported Red.
	measure 'Red Areas' = CALCULATE(COUNTROWS('Status Report Area'), 'Status Report Area'[Area Status] = "Red")
		formatString: #,0
		displayFolder: Health
		lineageTag: c3dcfdf2-2c0c-5e5c-9697-34b35874ff10

	/// Knowledge-area entries reported Yellow.
	measure 'Yellow Areas' = CALCULATE(COUNTROWS('Status Report Area'), 'Status Report Area'[Area Status] = "Yellow")
		formatString: #,0
		displayFolder: Health
		lineageTag: c0ada9ad-2111-5b40-8183-8ae728d15bc3

	/// Knowledge-area entries reported Green.
	measure 'Green Areas' = CALCULATE(COUNTROWS('Status Report Area'), 'Status Report Area'[Area Status] = "Green")
		formatString: #,0
		displayFolder: Health
		lineageTag: dd5709f6-80a0-5f04-8db8-e801cbdf4819

	/// Selected project name for the status report header.
	measure 'Theragen Project Name' = SELECTEDVALUE('Project'[Project Name], "All projects - select one")
		displayFolder: Status Page
		lineageTag: 98668fcf-da25-5a18-bdab-0655f35e9200

	/// Selected project's PM for the status report header.
	measure 'Project Manager (Selected)' = SELECTEDVALUE('Project'[Project Manager], "-")
		displayFolder: Status Page
		lineageTag: 221871aa-f5b4-58b2-b1ab-bc6d83c22d59

	/// Planned finish of the selected project; TBD when not set.
	measure 'Target Date Completion' = VAR d = MAX('Project'[Planned Finish]) RETURN IF(ISBLANK(d), "TBD", FORMAT(d, "M/D/YYYY"))
		displayFolder: Status Page
		lineageTag: 034860cc-b8cc-522f-83d5-7105dffc7f90

	/// Current PMI process group of the selected project.
	measure 'Current Phase' = SELECTEDVALUE('Project'[Lifecycle Phase], "Multiple")
		displayFolder: Status Page
		lineageTag: 2f7e7543-1dbe-54ac-97db-8a06b6147d84

	/// Traffic-light letter from the latest status report: G / Y / R.
	measure 'Main Status' = SWITCH([Latest Overall Status], "Green", "G", "Yellow", "Y", "Red", "R", BLANK())
		displayFolder: Status Page
		lineageTag: e8cb2cb1-0c75-5467-9a4b-105d6795f90d

	/// Hex color for the Main Status traffic light. Values match the Theragen status deck exactly (G #107C10 / Y #C19C00 / R #C0392B).
	measure 'Status Color' = SWITCH([Latest Overall Status], "Green", "#107C10", "Yellow", "#C19C00", "Red", "#C0392B", "#605E5C")
		displayFolder: Status Page
		lineageTag: 495d00ce-0523-5917-9d70-ec78cda231c7

	/// Project description text block.
	measure 'Project Description (Selected)' = SELECTEDVALUE('Project'[Project Description], "Select a single project")
		displayFolder: Status Page
		lineageTag: 0b899626-94d0-55db-91f0-8af7b2f95bd9

	/// Business value text block (charter business case).
	measure 'Business Value (Selected)' = SELECTEDVALUE('Project'[Business Value], "Select a single project")
		displayFolder: Status Page
		lineageTag: ebf46e41-7f7c-522f-87fd-a9bddf7c7247

	/// Health-check status of a knowledge area from the most recent report.
	measure 'Latest Area Status' = VAR d0 = MAX('Status Report'[Period End]) RETURN CALCULATE(MAX('Status Report Area'[Area Status]), 'Status Report'[Period End] = d0)
		displayFolder: Status Page
		lineageTag: 20ae75ec-02a7-54f8-bdf1-b0ccd4215a85

	/// Date of the latest status report.
	measure 'Report Date' = VAR d = MAX('Status Report'[Period End]) RETURN IF(ISBLANK(d), "-", FORMAT(d, "M/D/YYYY"))
		displayFolder: Status Page
		lineageTag: 998c5096-cc59-589f-bc41-707e6e749a31

	/// Open decisions called out in the latest status report.
	measure 'Decisions Needed (Latest)' = VAR d0 = MAX('Status Report'[Period End]) RETURN CALCULATE(MAX('Status Report'[Decisions Needed]), 'Status Report'[Period End] = d0)
		displayFolder: Status Page
		lineageTag: 037df3da-7708-5661-8d45-7f65ff2ffa17

	/// Earliest planned start of activities in context (workstream start date).
	measure 'Workstream Start' = MIN('Schedule Activity'[Planned Start])
		formatString: yyyy-mm-dd
		displayFolder: Status Page
		lineageTag: 1d8e8ed3-aee2-5c1c-9656-c5d6ecb682d0

	/// Latest planned finish of activities in context (target implementation date).
	measure 'Workstream Target' = MAX('Schedule Activity'[Planned Finish])
		formatString: yyyy-mm-dd
		displayFolder: Status Page
		lineageTag: e71d2bca-fbed-5bac-858f-a5a7ef47b314

	/// Roll-up status per workstream: COMPLETED / AT RISK / NOT STARTED / ON TRACK.
	measure 'Workstream Status' = VAR tot = [Activities] VAR done = [Activities Done] VAR atRisk = [Activities At Risk] + [Activities Overdue] VAR started = [Activities In Progress] + done RETURN SWITCH(TRUE(), ISBLANK(tot) || tot = 0, "-", done = tot, "COMPLETED", atRisk > 0, "AT RISK", started = 0, "NOT STARTED", "ON TRACK")
		displayFolder: Status Page
		lineageTag: 7cfeaba1-105b-5d12-828a-439297e3a942

	/// Legend for status letters (matches the Theragen status report key).
	measure 'Status Key' = "KEY:   G = Green   |   Y = Yellow   |   R = Off Track   |   C = Completed   |   NS = Not Started   |   H = Hold   |   CN = Cancelled"
		displayFolder: Status Page
		lineageTag: 2733fac0-5906-5cfe-baa5-1d4060cac0d6

	/// Legend for PMI lifecycle phases used on this report.
	measure 'Phase Key' = "PHASES:   Initiating - Planning - Executing - Monitoring - Closing"
		displayFolder: Status Page
		lineageTag: 9cd09a2c-54f0-5651-bb63-f0b03d66200a

	/// Stakeholder register entries.
	measure Stakeholders = COUNTROWS('Stakeholder')
		formatString: #,0
		displayFolder: Stakeholders
		lineageTag: 10aa4498-e4e9-5877-83ce-f429d8aeb748

	/// Influence = High.
	measure 'High Influence Stakeholders' = CALCULATE([Stakeholders], 'Stakeholder'[Influence] = "High")
		formatString: #,0
		displayFolder: Stakeholders
		lineageTag: f9e09000-9fd7-5a2b-b1a4-e2c2891093c1

	/// High interest and high influence (manage closely).
	measure 'Key Players' = CALCULATE([Stakeholders], 'Stakeholder'[Influence] = "High", 'Stakeholder'[Interest] = "High")
		formatString: #,0
		displayFolder: Stakeholders
		lineageTag: 1adffced-044b-536f-a9a3-872f27168a8e

	/// RACI = Accountable.
	measure 'Accountable Count' = CALCULATE([Stakeholders], 'Stakeholder'[Engagement] = "A")
		formatString: #,0
		displayFolder: Stakeholders
		lineageTag: fc15ce16-e751-526d-a2f7-a4385cee7ec2

	/// RACI = Responsible.
	measure 'Responsible Count' = CALCULATE([Stakeholders], 'Stakeholder'[Engagement] = "R")
		formatString: #,0
		displayFolder: Stakeholders
		lineageTag: 1be9bdd7-eb42-5035-b868-66aef08a6ed0

	/// Team assignments.
	measure 'Team Members' = COUNTROWS('Team Member')
		formatString: #,0
		displayFolder: Team
		lineageTag: 5349c225-a470-5253-b5ac-012fe0c3c48c

	/// Sum of allocation percentages as full-time equivalents.
	measure 'Total FTE' = SUM('Team Member'[Allocation Pct]) / 100
		formatString: #,0.0
		displayFolder: Team
		lineageTag: a947b3be-b4c3-5868-ad17-9edb7a1bac1c

	/// Mean allocation per assignment.
	measure 'Avg Allocation Pct' = AVERAGE('Team Member'[Allocation Pct]) / 100
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Team
		lineageTag: 2368ff5b-06b2-5582-920b-1565ed3367d8

	/// Lessons captured.
	measure Lessons = COUNTROWS('Lesson Learned')
		formatString: #,0
		displayFolder: Closing
		lineageTag: 19cfe555-d868-5349-96bb-594c7b403b2c

	/// Lessons awaiting action.
	measure 'Open Lessons' = CALCULATE([Lessons], 'Lesson Learned'[Lesson Status] = "Open")
		formatString: #,0
		displayFolder: Closing
		lineageTag: f4454050-19e9-557f-af41-667d512d9b5f

	/// Lessons adopted into practice.
	measure 'Adopted Lessons' = CALCULATE([Lessons], 'Lesson Learned'[Lesson Status] = "Adopted")
		formatString: #,0
		displayFolder: Closing
		lineageTag: 8bf0d301-0214-57dd-8449-562a57dfad61

	/// Closure checklist items.
	measure 'Closure Items' = COUNTROWS('Closure Item')
		formatString: #,0
		displayFolder: Closing
		lineageTag: 0808081c-b3c4-5c7b-a977-ceee5ae08207

	/// Checklist items complete.
	measure 'Closure Items Done' = CALCULATE([Closure Items], 'Closure Item'[Done] = TRUE())
		formatString: #,0
		displayFolder: Closing
		lineageTag: aea6ec20-196f-510e-be1c-521f9f73fa48

	/// Closure checklist completion.
	measure 'Closure Complete Pct' = DIVIDE([Closure Items Done], [Closure Items])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Closing
		lineageTag: 36753eb4-39b8-514e-89de-1a17d248c94f

	/// Mean L x I score of open risks on the 1-25 scale. Gauge value.
	measure 'Avg Risk Score (Open)' = CALCULATE(AVERAGE('Risk'[Risk Score]), 'Risk'[Risk Status] IN {"Open", "Mitigating", "Monitoring"})
		formatString: #,0.0
		displayFolder: Risk
		lineageTag: 077a85b1-ab0b-5068-ae2e-5c8618e29eb6

	/// Mean likelihood (1-5) of open risks.
	measure 'Avg Likelihood (Open)' = CALCULATE(AVERAGE('Risk'[Likelihood]), 'Risk'[Risk Status] IN {"Open", "Mitigating", "Monitoring"})
		formatString: #,0.0
		displayFolder: Risk
		lineageTag: 16e3fae0-c328-5398-9962-61c2acaf3118

	/// Mean impact (1-5) of open risks.
	measure 'Avg Impact (Open)' = CALCULATE(AVERAGE('Risk'[Impact]), 'Risk'[Risk Status] IN {"Open", "Mitigating", "Monitoring"})
		formatString: #,0.0
		displayFolder: Risk
		lineageTag: 70b9afa3-cc9e-519f-85ad-afaa812d8de6

	/// Mean residual score of open risks after planned mitigation.
	measure 'Avg Residual Score (Open)' = CALCULATE(AVERAGE('Risk'[Residual Score]), 'Risk'[Risk Status] IN {"Open", "Mitigating", "Monitoring"})
		formatString: #,0.0
		displayFolder: Risk
		lineageTag: 281deb74-cb7c-5943-b6b1-0981cb04f37c

	/// Severity index: average open-risk score normalized to the 5x5 maximum (25).
	measure 'Risk Index' = DIVIDE([Avg Risk Score (Open)], 25)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Risk
		lineageTag: a98f53a9-a12a-59fe-850b-64db7c7432ba

	/// Banded rating of the average open-risk score: <6 LOW, <12 MODERATE, <20 HIGH, else CRITICAL.
	measure 'Risk Rating' = SWITCH(TRUE(), ISBLANK([Avg Risk Score (Open)]), "-", [Avg Risk Score (Open)] < 6, "LOW", [Avg Risk Score (Open)] < 12, "MODERATE", [Avg Risk Score (Open)] < 20, "HIGH", "CRITICAL")
		displayFolder: Risk
		lineageTag: 2e02615d-9e46-52d2-b94b-644592d47e44

	/// Deck-aligned color for the Risk Rating band (conditional formatting).
	measure 'Risk Rating Color' = SWITCH([Risk Rating], "LOW", "#107C10", "MODERATE", "#C19C00", "HIGH", "#C0392B", "CRITICAL", "#8B1A1A", "#605E5C")
		displayFolder: Risk
		lineageTag: e010621b-6518-54d3-9d7d-2fd9fb4a8bfb

	/// Maximum of the 5x5 risk matrix. Gauge maximum.
	measure 'Risk Scale Max' = 25
		formatString: #,0
		displayFolder: Risk
		lineageTag: 83d511bd-ec86-5fc2-8f43-26b0efd75fa1

	/// Score at which a risk is rated High (>=12). Gauge target line.
	measure 'High Risk Threshold' = 12
		formatString: #,0
		displayFolder: Risk
		lineageTag: ea9e64fe-9b39-5558-b0bc-4fe2e9ca2b6a

	/// Share of open risks that have at least one response action planned.
	measure 'Mitigation Coverage %' = DIVIDE(COUNTROWS(FILTER(CALCULATETABLE('Risk', 'Risk'[Risk Status] IN {"Open", "Mitigating", "Monitoring"}), CALCULATE(COUNTROWS('Risk Response')) > 0)), [Open Risks])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Risk
		lineageTag: 289f7f2f-d7ea-5719-b1cd-c9575dc4ca53

	/// Deck-exact font color for the Health Check status column (conditional formatting).
	measure 'Area Status Color' = SWITCH([Latest Area Status], "Green", "#107C10", "Yellow", "#C19C00", "Red", "#C0392B", "#252423")
		displayFolder: Status Page
		lineageTag: 958ebaa8-26df-5932-9b89-25f5f53be24d

	/// Deck-exact font color for the Key Project Areas status column (conditional formatting).
	measure 'Workstream Status Color' = SWITCH([Workstream Status], "ON TRACK", "#107C10", "AT RISK", "#C19C00", "#252423")
		displayFolder: Status Page
		lineageTag: 47d79d39-a654-507b-9139-f95bfd2c439b

	/// Approved CRs with implementation confirmed in the artifact library.
	measure 'Verified CRs' = CALCULATE([Change Requests], 'Change Request'[Implementation Verified] = TRUE())
		formatString: #,0
		displayFolder: Change
		lineageTag: 58b0a9c7-aa60-5d23-a755-78059b7b9f5c

	/// Approved CRs awaiting implementation verification.
	measure 'CRs Pending Verification' = CALCULATE([Change Requests], 'Change Request'[Decision] = "Approved", 'Change Request'[Implementation Verified] = FALSE())
		formatString: #,0
		displayFolder: Change
		lineageTag: a069414d-ba1a-5667-98b9-5fe155571303

	/// Governance decisions formally logged for the project(s) in context.
	measure 'Decisions Logged' = COUNTROWS('Decision')
		formatString: #,0
		displayFolder: Change
		lineageTag: fd0f7788-ad8c-599b-92f9-158ea2980c2f

	/// Status reports that have been formally signed off by the approver.
	measure 'Signed-off Reports' = CALCULATE(COUNTROWS('Status Report'), 'Status Report'[Is Signed Off] = TRUE())
		formatString: #,0
		displayFolder: Health
		lineageTag: 50927f3f-d9c4-5f55-a9f0-bd1243b63219

	/// Proportion of status reports that have been signed off.
	measure 'Sign-off Rate' = DIVIDE([Signed-off Reports], COUNTROWS('Status Report'))
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Health
		lineageTag: 7cddf0e9-d3c7-5497-9a4d-0d6d70572efe

	/// Count of baseline rows in context (all versions and statuses).
	measure Baselines = COUNTROWS('Project Baseline')
		formatString: #,0
		displayFolder: Baselines
		lineageTag: 3869e811-dccb-565e-ab52-f4d59d2c4619

	/// Baselines that are currently the active (BASELINED) version.
	measure 'Current Baselines' = CALCULATE([Baselines], 'Project Baseline'[Status] = "BASELINED")
		formatString: #,0
		displayFolder: Baselines
		lineageTag: f9256661-a0a6-5cdb-88e1-43002cc190e1

	/// Active Schedule baseline version (highest among BASELINED).
	measure 'Current Schedule Baseline Version' = CALCULATE(MAX('Project Baseline'[Version]), 'Project Baseline'[Baseline Type] = "Schedule", 'Project Baseline'[Status] = "BASELINED")
		displayFolder: Baselines
		lineageTag: 80ceeac1-b816-5e49-8273-18b351cd00a8

	/// Active Budget baseline version (highest among BASELINED).
	measure 'Current Budget Baseline Version' = CALCULATE(MAX('Project Baseline'[Version]), 'Project Baseline'[Baseline Type] = "Budget", 'Project Baseline'[Status] = "BASELINED")
		displayFolder: Baselines
		lineageTag: f4ea8366-d602-539b-8fb2-47e80c61897f

	/// Active Scope baseline version (highest among BASELINED).
	measure 'Current Scope Baseline Version' = CALCULATE(MAX('Project Baseline'[Version]), 'Project Baseline'[Baseline Type] = "Scope", 'Project Baseline'[Status] = "BASELINED")
		displayFolder: Baselines
		lineageTag: c7076e70-ef14-5a83-be46-c54eb00bc32c

	/// Drift of the current approved budget from the frozen BASELINED Budget baseline (current charter budget minus the baseline's snapshot budget_total). Positive = budget grew since baseline.
	measure 'Budget Variance vs Baseline' = SUM('Project'[Charter Budget]) - SUMX(FILTER('Project Baseline', 'Project Baseline'[Baseline Type]="Budget" && 'Project Baseline'[Status]="BASELINED"), 'Project Baseline'[Baseline Budget Total])
		formatString: \$#,##0;(\$#,##0);\$0
		displayFolder: Baselines
		lineageTag: 64b76302-82ca-5022-8e9e-7920da18f309

	/// Phase gates that advanced the project a real step forward (Approved / Approved with conditions, From != To).
	measure 'Phase Gates Passed' = COUNTROWS(FILTER('Phase Gate Log', 'Phase Gate Log'[Gate Decision] IN {"Approved", "Approved with conditions"} && 'Phase Gate Log'[From Phase] <> 'Phase Gate Log'[To Phase]))
		formatString: #,0
		displayFolder: Governance
		lineageTag: e2924bed-b7e5-55be-8fbc-a1e52031ae88

	/// Phase gates where the decision was Held.
	measure 'Gates Held' = CALCULATE(COUNTROWS('Phase Gate Log'), 'Phase Gate Log'[Gate Decision] = "Held")
		formatString: #,0
		displayFolder: Governance
		lineageTag: 626203aa-875e-56bd-bfdf-daef6cb736ab

	/// Count of per-department impact assessments.
	measure 'Impact Assessments' = COUNTROWS('Change Impact Assessment')
		formatString: #,0
		displayFolder: Change
		lineageTag: 2a83e2ad-6285-5065-8404-cae8c1196c71

	/// Distinct CRs with at least one impact assessment.
	measure 'Assessed CRs' = DISTINCTCOUNT('Change Impact Assessment'[CR ID])
		formatString: #,0
		displayFolder: Change
		lineageTag: fea4de75-2782-544d-be93-212816d88d31

	/// Distinct departments that assessed a CR.
	measure 'Departments Assessed' = DISTINCTCOUNT('Change Impact Assessment'[Department])
		formatString: #,0
		displayFolder: Change
		lineageTag: e31202c1-f2bb-581e-aa6a-e0a2d7130ab7

	/// Total assessed schedule impact across departments (days).
	measure 'Assessed Schedule Impact Days' = SUM('Change Impact Assessment'[Schedule Impact Days])
		formatString: #,0
		displayFolder: Change
		lineageTag: fc0c0538-55e6-5775-886f-b95e11fadd79

	/// Total assessed cost impact across departments.
	measure 'Assessed Cost Impact' = SUM('Change Impact Assessment'[Cost Impact])
		formatString: \$#,##0;(\$#,##0);\$0
		displayFolder: Change
		lineageTag: d1486865-f1a0-55dc-96de-d2cfe1afa0e4

	/// Count of controlled documents.
	measure 'Controlled Documents' = COUNTROWS('Controlled Document')
		formatString: #,0
		displayFolder: Documents
		lineageTag: d54d91f1-8d37-5f70-abea-94006c539899

	/// Documents in DRAFT.
	measure 'Draft Documents' = CALCULATE([Controlled Documents], 'Controlled Document'[Status] = "DRAFT")
		formatString: #,0
		displayFolder: Documents
		lineageTag: bcc85fab-8d8a-5b43-a6f8-c2b61d850102

	/// Documents at BASELINE.
	measure 'Baseline Documents' = CALCULATE([Controlled Documents], 'Controlled Document'[Status] = "BASELINE")
		formatString: #,0
		displayFolder: Documents
		lineageTag: 5d65c7db-b12e-55d2-8b8c-43e2217019f5

	/// Documents retired.
	measure 'Retired Documents' = CALCULATE([Controlled Documents], 'Controlled Document'[Status] = "RETIRED")
		formatString: #,0
		displayFolder: Documents
		lineageTag: 9495c90c-f914-5c95-844b-3e95e865267b

	/// Active documents past their next review date.
	measure 'Documents Due for Review' = CALCULATE([Controlled Documents], FILTER('Controlled Document', NOT ISBLANK('Controlled Document'[Next Review Due]) && 'Controlled Document'[Next Review Due] <= TODAY() && 'Controlled Document'[Status] <> "RETIRED"))
		formatString: #,0
		displayFolder: Documents
		lineageTag: 0e28cfdb-83bf-5620-8134-6265dce80c96

	/// Count of document RACI assignments.
	measure 'RACI Assignments' = COUNTROWS('Document RACI')
		formatString: #,0
		displayFolder: Documents
		lineageTag: 8fdb6b83-e380-5a16-97b3-d4c768e4fa41

	/// Documents that have at least one RACI assignment.
	measure 'Documents with RACI' = DISTINCTCOUNT('Document RACI'[Document ID])
		formatString: #,0
		displayFolder: Documents
		lineageTag: 73685f83-475a-558b-a7a8-8b8a6ef42539

	/// RACI rows with the Accountable role.
	measure 'Accountable Assignments' = CALCULATE([RACI Assignments], 'Document RACI'[Role] = "A")
		formatString: #,0
		displayFolder: Documents
		lineageTag: 9ef1eab1-2230-5177-ba18-bde9d74206eb

	/// RACI rows with the Responsible role.
	measure 'Responsible Assignments' = CALCULATE([RACI Assignments], 'Document RACI'[Role] = "R")
		formatString: #,0
		displayFolder: Documents
		lineageTag: 4f839f6f-186b-5d61-8557-9cab7be6ce82

	/// RACI assignments currently in effect (open-ended or not yet expired).
	measure 'Current RACI Assignments' = CALCULATE([RACI Assignments], FILTER('Document RACI', ISBLANK('Document RACI'[Valid To]) || 'Document RACI'[Valid To] >= TODAY()))
		formatString: #,0
		displayFolder: Documents
		lineageTag: 67050f18-35d3-5ce2-9244-b482e1a75183

	/// Count of controlled-document versions.
	measure 'Document Versions' = COUNTROWS('Document Version')
		formatString: #,0
		displayFolder: Documents
		lineageTag: 07aa2dc9-463d-5419-b265-54dea4c0103c

	/// Versions at BASELINE.
	measure 'Baseline Versions' = CALCULATE([Document Versions], 'Document Version'[Status] = "BASELINE")
		formatString: #,0
		displayFolder: Documents
		lineageTag: b6ec2811-37f6-5b1a-a4c6-73efba32ad18

	/// Count of sign-off attestations (non-Part-11; see 'Document Approval'[Attestation Kind]).
	measure 'Document Approvals' = COUNTROWS('Document Approval')
		formatString: #,0
		displayFolder: Documents
		lineageTag: 87d4af8c-736f-54b0-9014-f054a8da1e1f

	/// Distinct versions carrying at least one attestation.
	measure 'Attested Versions' = DISTINCTCOUNT('Document Approval'[Version ID])
		formatString: #,0
		displayFolder: Documents
		lineageTag: 98275026-48da-5aab-a70a-c364274499e1

	/// Attestations whose meaning is Approval.
	measure 'Approval Attestations' = CALCULATE([Document Approvals], 'Document Approval'[Signature Meaning] = "Approval")
		formatString: #,0
		displayFolder: Documents
		lineageTag: 11c5f746-815a-56f2-b7f0-f48c9511e087

	/// Governance change requests against controlled documents (CHG-NNN).
	measure 'Governance CRs' = COUNTROWS('Governance Change Request')
		formatString: #,0
		displayFolder: Change
		lineageTag: aea05c8b-3236-5d5f-99ec-ee64005a80d8

	/// Governance CRs not yet closed.
	measure 'Open Governance CRs' = CALCULATE([Governance CRs], 'Governance Change Request'[Status] = "Open")
		formatString: #,0
		displayFolder: Change
		lineageTag: 6c78624e-c5c7-5a24-8c08-929620bb0933

	/// Governance CRs whose decision is Approved.
	measure 'Approved Governance CRs' = CALCULATE([Governance CRs], 'Governance Change Request'[Decision] = "Approved")
		formatString: #,0
		displayFolder: Change
		lineageTag: ae84623c-56ff-530c-911b-0595a40fe8bd

	/// Governance CRs whose implementation has been verified (mirrors Verified CRs).
	measure 'Verified Governance CRs' = CALCULATE([Governance CRs], 'Governance Change Request'[Implementation Verified] = TRUE())
		formatString: #,0
		displayFolder: Change
		lineageTag: 82158f4f-f5af-5404-8e8c-e84a7dbdbe3e

	/// Per-department impact assessments on governance CRs.
	measure 'Governance Assessments' = COUNTROWS('Governance Change Assessment')
		formatString: #,0
		displayFolder: Change
		lineageTag: 12ae2f06-effa-5736-b982-afe4a5fff733

	/// Distinct governance CRs that have at least one department assessment.
	measure 'Assessed Governance CRs' = DISTINCTCOUNT('Governance Change Assessment'[CR Gov ID])
		formatString: #,0
		displayFolder: Change
		lineageTag: d3730271-c3cb-50b6-8d87-e5c635a2b272

	column Value
		dataType: string
		isHidden
		lineageTag: 5b25cfc3-5d37-5fa2-961a-05daa1eb43ca
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = User

	/// Per-risk response actions (Mitigation / Transfer / Acceptance / Avoidance).
	measure 'Risk Actions' = COUNTROWS('Risk Response')
		formatString: #,0
		displayFolder: Risk
		lineageTag: a0ab180c-1312-5471-aca8-afaffd6aa563

	/// Response actions not yet Done.
	measure 'Open Risk Actions' = CALCULATE([Risk Actions], 'Risk Response'[Action Status] <> "Done")
		formatString: #,0
		displayFolder: Risk
		lineageTag: aba94260-e05e-5500-942e-29b507ef13fe

	/// Open response actions past their due date.
	measure 'Overdue Risk Actions' = COUNTROWS(FILTER('Risk Response', NOT ISBLANK('Risk Response'[Action Due Date]) && 'Risk Response'[Action Due Date] < TODAY() && 'Risk Response'[Action Status] <> "Done"))
		formatString: #,0
		displayFolder: Risk
		lineageTag: f574723b-0876-5054-a5a0-077bd3b8de30

	/// AC - cumulative actual cost to date (sum of logged cost actuals).
	measure 'AC (Actual Cost)' = SUM('Cost Actual'[Amount])
		formatString: \$#,##0;(\$#,##0);\$0
		displayFolder: EVM
		lineageTag: 222842a7-48fc-5fb4-80a9-e8a17db795df

	/// CV = EV - AC. Negative = over budget.
	measure 'Cost Variance (CV)' = [Earned Value] - [AC (Actual Cost)]
		formatString: \$#,##0;(\$#,##0);\$0
		displayFolder: EVM
		lineageTag: 1aa07da3-d1a8-5696-991a-4661b8bc5e73

	/// Cost Performance Index = EV / AC. Below 1.0 = over budget.
	measure CPI = DIVIDE([Earned Value], [AC (Actual Cost)])
		formatString: 0.00
		displayFolder: EVM
		lineageTag: 05f53f7c-f8a7-56ea-bb7e-9208771dc9bd

	/// Estimate at Completion = BAC / CPI (performance-based forecast).
	measure EAC = DIVIDE([BAC (WBS Estimates)], [CPI])
		formatString: \$#,##0;(\$#,##0);\$0
		displayFolder: EVM
		lineageTag: 671440f9-bd1b-5ee7-92fa-5e5af1d2e7a3

	/// Variance at Completion = BAC - EAC. Negative = projected overrun.
	measure VAC = [BAC (WBS Estimates)] - [EAC]
		formatString: \$#,##0;(\$#,##0);\$0
		displayFolder: EVM
		lineageTag: 4a2e2164-3ea6-5eee-a8bd-493572d4879c

	/// To-Complete Performance Index = (BAC - EV) / (BAC - AC). Above 1.0 = tighter cost control needed to finish on budget.
	measure TCPI = DIVIDE([BAC (WBS Estimates)] - [Earned Value], [BAC (WBS Estimates)] - [AC (Actual Cost)])
		formatString: 0.00
		displayFolder: EVM
		lineageTag: 09861b0e-c2b5-58a4-ba01-a8105a0c06b6

	partition _Measures = m
		mode: import
		source =
				let
				    Source = Table.FromRows({}, {"Value"}),
				    Typed = Table.TransformColumnTypes(Source, {{"Value", type text}})
				in
				    Typed

	annotation PBI_ResultType = Table

